syntax = "proto3";
package cds.distdownloader.v1;

import "common.proto";

option java_multiple_files = true;
option java_package = "cds.distdownloader.proto";

// Peer sends this periodically (ex: every 5s).
message HeartbeatRequest {
  PeerEndpoint endpoint = 1;
  repeated FileManifestEntry files = 2;
}
message HeartbeatResponse {
  Ack ack = 1;
  string peer_id = 2;
}

message GetFileManifestRequest {
  string file_id = 1;
}

message GetFileManifestResponse {
  FileManifestEntry file = 1;
}

//Peer sends final manifest entry to tracker
message FileManifestEntry {
  string filename = 1;
  int64 filesize = 2;
  int32 chunk_size = 3;
  string origin = 4;
  string hash_algorithm = 5;
  int32 num_chunks = 6;
}

// Returns only currently-up peers (not expired by TTL).
message ListPeersRequest {
  // empty: client sends request, tracker doesn't do anything
}
message ListPeersResponse {
  repeated PeerEndpoint up_peers = 1;
}

service Tracker {
  rpc HandleHeartbeatRequest(HeartbeatRequest) returns (HeartbeatResponse);
  rpc HandleListPeersRequest(ListPeersRequest) returns (ListPeersResponse);
  rpc GetFileManifest(GetFileManifestRequest) returns (GetFileManifestResponse);
}
